version: '3'

services: 
    laravel-app:
        build: .
        ports: 
            - "8080:80"
        volumes: 
            - ./:/usr/share/nginx
        networks: 
            - app-network
    
    mysql:
        image: mysql:5.7.22
        ports: 
           - "3306:3306"
        volumes: 
            - .docker/dbtata:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: agenda_clinica_exemplo
            MYSQL_ROOT_PASSWORD: 
        networks: 
            - app-network

networks: 
    app-network:
        driver: bridge